version: '3.8'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13644631
      POSTGRES_DB: student_system
    ports:
      - "5432:5432"
